name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup deps
        run: |
          sudo apt update
          sudo apt install -y libmpv-dev pkg-config

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --workspace
